name: Deploy Website

on:
  push:
    branches:
      - "main"

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: 'Build'
        shell: bash
        run: |
          echo "::group::Build"
          npm ci
          npm run build
          echo "::endgroup::"
      - name: 'upload'
        uses: actions/upload-pages-artifact@v3
        with: 
          path: build

      - id: deploy
        name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          token: ${{ github.token }}